# Cloudflare Pages with Functions configuration
name = "charades-generator"
compatibility_date = "2024-01-01"

# Pages configuration
pages_build_output_dir = ".vercel/output/static"

# Preview environment
[env.preview]
kv_namespaces = [
  { binding = "FEEDBACK_KV", id = "feedback-preview" }
]

# Production environment
[env.production]
kv_namespaces = [
  { binding = "FEEDBACK_KV", id = "feedback-production" }
]