# Cloudflare Pages with Functions configuration
name = "charades-generator"
compatibility_date = "2024-01-01"

# KV Namespace bindings for feedback storage
[[kv_namespaces]]
binding = "FEEDBACK_KV"
id = "feedback-storage"  # Will be replaced with actual namespace ID when deployed

# Local development KV namespace
[env.development]
kv_namespaces = [
  { binding = "FEEDBACK_KV", id = "feedback-dev", preview_id = "feedback-dev-preview" }
]

# Production environment (Cloudflare Pages will handle this)
[env.production]
# KV namespaces will be bound through CF Pages dashboard