# Cloudflare Workers configuration for local development
name = "charades-generator-dev"
main = ".vercel/output/static/_worker.js"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

# Local development
[env.development]
vars = { NODE_ENV = "development" }

# KV Namespace bindings for local development
[[kv_namespaces]]
binding = "FEEDBACK_KV"
id = "051dfaa61eea42d78d464e62dae7cb09"
preview_id = "64c1f557dc834e5dbb152b4a434d2bb1"

# Wrangler dev configuration
[dev]
port = 8787
local_protocol = "http"
upstream_protocol = "https"