# Cloudflare Pages with Functions configuration
name = "charades-generator"
compatibility_date = "2024-01-01"

# Pages configuration
pages_build_output_dir = ".vercel/output/static"

# Note: KV namespaces should be configured through Cloudflare Pages Dashboard
# Go to your Pages project > Settings > Functions > KV namespace bindings
# Add binding: FEEDBACK_KV -> your-kv-namespace